# Config file for automatic testing at travis-ci.org

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - 3.6
  - 3.5
install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive ghostscript
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
  - bash miniconda3.sh -b -p $HOME/miniconda3
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - conda activate
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION
  - conda activate test_env
  - conda config --append channels conda-forge
  - conda install qutip
  - pip install .[simulation,visualization,dev]

script:
  - pytest --doctest-modules --cov=qnet src tests docs/*.rst
after_success:
  - coveralls
